# Generated by Django 4.2.15 on 2024-08-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Forum",
            new_name="Foruma",
        ),
    ]
